# Generated by Django 3.1.7 on 2021-04-01 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_community_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='title',
        ),
    ]
