# Generated by Django 3.1.7 on 2021-03-24 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='image_upload',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='text',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='title',
        ),
        migrations.AddField(
            model_name='plant',
            name='common_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='family',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='publication_year',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
