# Generated by Django 3.1.7 on 2021-03-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20210324_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='foreign_key',
            field=models.SmallIntegerField(null=True, unique=True),
        ),
    ]
