# Generated by Django 3.1.7 on 2021-03-24 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plants', '0003_plant_foreign_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='foreign_key',
        ),
        migrations.AddField(
            model_name='plant',
            name='api_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
