# Generated by Django 3.1.7 on 2021-04-02 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0010_auto_20210402_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='plants.plant'),
        ),
    ]
